/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uCzQ0gDwPIo
 */
import Link from "next/link"
import { NavigationMenuLink, NavigationMenuList, NavigationMenu } from "@/components/ui/navigation-menu"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"

export function LegalDocumentAnalysisComponent() {
  return (
    <div className="container mx-auto px-4 text-black">
      <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6">
        <Link className="mr-6 text-black" href="#" >
          <CopyrightIcon className="h-6 w-6" />
          <span className="sr-only">Legal Document Analysis Inc</span>
        </Link>
        <NavigationMenu className="ml-auto">
          <NavigationMenuList>
            <NavigationMenuLink asChild>
              <Link href="#">Home</Link>
            </NavigationMenuLink>
            <NavigationMenuLink asChild>
              <Link href="#">About</Link>
            </NavigationMenuLink>
            <NavigationMenuLink asChild>
              <Link href="#">Services</Link>
            </NavigationMenuLink>
            <NavigationMenuLink asChild>
              <Link href="#">Contact</Link>
            </NavigationMenuLink>
          </NavigationMenuList>
        </NavigationMenu>
      </header>
      <main className="my-8">
        <section className="mb-8">
          <h1 className="text-4xl font-bold mb-4">Legal Document Analysis</h1>
          <p className="text-lg text-gray-600">
            Upload your legal documents and get instant insights and recommendations.
          </p>
        </section>
        <section className="mb-8">
          <div className="grid w-full max-w-sm items-center gap-1.5">
            <Label htmlFor="document">Upload Document</Label>
            <Input id="document" type="file" />
            <Button className="bg-black text-white">Upload</Button>
          </div>
        </section>
        <section>
          <h2 className="text-3xl font-bold mb-4">Analysis Results</h2>
          <Card className="mb-4">
            <CardHeader>
              <h3 className="text-2xl font-bold">Key Insights</h3>
            </CardHeader>
            <CardContent>
              <p className="text-lg text-gray-600">Here are the key insights from the analysis of your document...</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <h3 className="text-2xl font-bold">Recommendations</h3>
            </CardHeader>
            <CardContent>
              <p className="text-lg text-gray-600">Based on our analysis, we recommend the following actions...</p>
            </CardContent>
          </Card>
        </section>
      </main>
    </div>
  )
}


function CopyrightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M15 9.354a4 4 0 1 0 0 5.292" />
    </svg>
  )
}
